/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import javax.swing.ImageIcon;
import model.Profile;

/**
 *
 * @author vagishadeo
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Profile profile;
    
    public ViewJPanel(Profile profile) {
        initComponents();
        
        this.profile = profile;
        displayProfile();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPhoto = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblUnique = new javax.swing.JLabel();
        txtBank = new javax.swing.JTextField();
        lblLinkedIn = new javax.swing.JLabel();
        iblTitle = new javax.swing.JLabel();
        lblDevice = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        txtDevice = new javax.swing.JTextField();
        txtMRN = new javax.swing.JTextField();
        lblIP = new javax.swing.JLabel();
        txtHPBN = new javax.swing.JTextField();
        txtLicense = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        lbltlele = new javax.swing.JLabel();
        lblBiometric = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        lblMRN = new javax.swing.JLabel();
        txtGeo = new javax.swing.JTextField();
        lblBank = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        lblLicence = new javax.swing.JLabel();
        txtBiometric = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        txtUnique = new javax.swing.JTextField();
        lblGeoData = new javax.swing.JLabel();
        txtVehicle = new javax.swing.JTextField();
        lblVehicle = new javax.swing.JLabel();
        lblHealth = new javax.swing.JLabel();
        lblfax = new javax.swing.JLabel();

        txtPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhotoActionPerformed(evt);
            }
        });

        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblPhoto.setText("Photo:");

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        lblEmail.setText("Email Address:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblUnique.setText("Unique Identifying Numbers:");

        txtBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankActionPerformed(evt);
            }
        });

        lblLinkedIn.setText("LinkedIn:");

        iblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        iblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iblTitle.setText("View Profile");

        lblDevice.setText("Device identifiers & serial numbers:");

        lblSSN.setText("Social Security Number:");

        txtDevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceActionPerformed(evt);
            }
        });

        txtMRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMRNActionPerformed(evt);
            }
        });

        lblIP.setText("Internet protocol addresses:");

        txtHPBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHPBNActionPerformed(evt);
            }
        });

        txtLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseActionPerformed(evt);
            }
        });

        lblName.setText("Name:");

        lbldob.setText("Date of Birth:");

        lbltlele.setText("Telephone Number:");

        lblBiometric.setText("Biometric Identifiers:");

        txtFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxActionPerformed(evt);
            }
        });

        txtLinkedin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedinActionPerformed(evt);
            }
        });

        lblMRN.setText("Media Record Number:");

        txtGeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeoActionPerformed(evt);
            }
        });

        lblBank.setText("Bank Account Numbers :");

        txtIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPActionPerformed(evt);
            }
        });

        lblLicence.setText("Certificate/License Number:");

        txtBiometric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBiometricActionPerformed(evt);
            }
        });

        txtTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneActionPerformed(evt);
            }
        });

        txtUnique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniqueActionPerformed(evt);
            }
        });

        lblGeoData.setText("Geographic Data:");

        txtVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleActionPerformed(evt);
            }
        });

        lblVehicle.setText("Vehicle identifiers & serial number:");

        lblHealth.setText("Health Plan Beneficiary Number:");

        lblfax.setText("Fax Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblGeoData)
                            .addComponent(lbldob)
                            .addComponent(lbltlele)
                            .addComponent(lblfax)
                            .addComponent(lblEmail)
                            .addComponent(lblSSN)
                            .addComponent(lblHealth)
                            .addComponent(lblMRN)
                            .addComponent(lblBank)
                            .addComponent(lblLicence)
                            .addComponent(lblPhoto)
                            .addComponent(lblLinkedIn)
                            .addComponent(lblBiometric)
                            .addComponent(lblIP)
                            .addComponent(lblVehicle)
                            .addComponent(lblDevice)
                            .addComponent(lblUnique))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIP)
                            .addComponent(txtBiometric, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(txtDevice)
                            .addComponent(txtLicense)
                            .addComponent(txtSSN)
                            .addComponent(txtEmail)
                            .addComponent(txtGeo)
                            .addComponent(txtFax)
                            .addComponent(txtTelephone)
                            .addComponent(txtHPBN)
                            .addComponent(txtBank)
                            .addComponent(txtDOB)
                            .addComponent(txtVehicle)
                            .addComponent(txtMRN)
                            .addComponent(txtLinkedin)
                            .addComponent(txtPhoto)
                            .addComponent(txtUnique)
                            .addComponent(txtName))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGeoData)
                                    .addComponent(txtGeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbldob))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltlele))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblfax))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblMRN)
                                .addGap(22, 22, 22)
                                .addComponent(lblHealth))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHPBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBank)
                            .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLicence))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVehicle)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(lblDevice)))
                                .addGap(18, 18, 18)
                                .addComponent(lblLinkedIn)
                                .addGap(18, 18, 18)
                                .addComponent(lblIP)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lblBiometric))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBiometric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPhoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnique))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhotoActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankActionPerformed

    private void txtDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceActionPerformed

    private void txtMRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMRNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMRNActionPerformed

    private void txtHPBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHPBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHPBNActionPerformed

    private void txtLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseActionPerformed

    private void txtFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxActionPerformed

    private void txtLinkedinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedinActionPerformed

    private void txtGeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeoActionPerformed

    private void txtIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPActionPerformed

    private void txtBiometricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBiometricActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiometricActionPerformed

    private void txtTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneActionPerformed

    private void txtUniqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniqueActionPerformed

    private void txtVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iblTitle;
    private javax.swing.JLabel lblBank;
    private javax.swing.JLabel lblBiometric;
    private javax.swing.JLabel lblDevice;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHealth;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblLicence;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMRN;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblUnique;
    private javax.swing.JLabel lblVehicle;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblfax;
    private javax.swing.JLabel lbltlele;
    private javax.swing.JTextField txtBank;
    private javax.swing.JTextField txtBiometric;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDevice;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtGeo;
    private javax.swing.JTextField txtHPBN;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoto;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtUnique;
    private javax.swing.JTextField txtVehicle;
    // End of variables declaration//GEN-END:variables

    private void displayProfile() {
         //To change body of generated methods, choose Tools | Templates.
       txtName.setText(profile.getName());
       txtGeo.setText(profile.getGeo_data());
       txtDOB.setText(profile.getDob());
       txtTelephone.setText(profile.getTele());
       txtFax.setText(profile.getFax());
       txtEmail.setText(profile.getEmail());
       txtEmail.setText(profile.getSsn());
       txtMRN.setText(profile.getMedia());
       txtHPBN.setText(profile.getHealth());
       txtBank.setText(profile.getBank_details());
       txtLicense.setText(profile.getLicense_number());
       txtVehicle.setText(profile.getVehicle_data());
       txtDevice.setText(profile.getDecice_data());
       txtLinkedin.setText(profile.getLinkedin());
       txtIP.setText(profile.getProtocol());
       txtBiometric.setText(profile.getBiometric());
       txtPhoto.setText(profile.getPhoto());
       txtUnique.setText(profile.getUnique_identify());
       
       String usephoto = profile.getPhoto();
       
       ImageIcon photo = new ImageIcon(usephoto);

       lblPhoto.setBounds(0,0, 708, 300);
       Image displayphoto = photo.getImage();
       Image picture = displayphoto.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
       ImageIcon edited = new ImageIcon(picture);
       lblPhoto.setIcon(edited);
       
       
      
       
        
    }
}
